{
 "title": "${ENVIRONMENT} - Databricks Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Succeeded Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "DatabricksJobs\r\n| where ActionName == \"runSucceeded\"\r\n| count",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.OperationalInsights/workspaces${RESOURCE_NAME}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Driver Node Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${DATABRICKS_MANAGED_RG}",
      "resourceName": "${DRIVER_NODE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Driver Node CPU Utilisation ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${DATABRICKS_MANAGED_RG}",
      "resourceName": "${DRIVER_NODE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "DatabricksJobs\r\n| where ActionName == \"runFailed\"\r\n| count",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.OperationalInsights/workspaces${RESOURCE_NAME}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Cluster Worker Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "DatabricksClusters\r\n| where ActionName == \"resizeResult\"\r\n| extend f=parse_json(RequestParams)\r\n| project TimeGenerated, toint(f.clusterWorkers)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.OperationalInsights/workspaces${RESOURCE_NAME}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Job Creation",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "DatabricksJobs\r\n| where ActionName == \"create\"\r\n| extend d=parse_json(Identity)\r\n| extend r=parse_json(Response)\r\n| extend p=parse_json(RequestParams)\r\n| project TimeGenerated, Email=d.email, JobName=p.name, Status=iif(r.statusCode==200, \"successfull\", r.errorMessage)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.OperationalInsights/workspaces${RESOURCE_NAME}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Failed Job Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "DatabricksJobs\r\n| where ActionName == \"runFailed\"\r\n| extend p=parse_json(RequestParams)\r\n| project TimeGenerated, CluserID=p.clusterId, ClusterType=p.jobClusterType, TaskType=p.jobTaskType, TerminalState=p.jobTerminalState, TriggerType=p.jobTriggerType, TaskKey=p.taskKey\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.OperationalInsights/workspaces${RESOURCE_NAME}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Cluster Edit Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "DatabricksClusters\r\n| where ActionName == \"edit\"\r\n| extend d=parse_json(Identity) \r\n| extend f=parse_json(RequestParams)\r\n//| project UserEmail=d.email f.autoscale.min_workers",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.OperationalInsights/workspaces${RESOURCE_NAME}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.operationalinsights/workspaces",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  }
 ]
}