{
 "title": "Infra Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "TBS VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Percentage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_HOST_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_IIS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_RMQ_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_HOST_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_IIS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_RMQ_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Disk IOPS Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Data Disk IOPS Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_HOST_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Data Disk IOPS Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_IIS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Data Disk IOPS Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_RMQ_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Network In Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network In Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_HOST_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network In Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_IIS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network In Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_RMQ_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Network Out Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network Out Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_HOST_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network Out Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_IIS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network Out Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBSVM_RESOURCE_GROUP}",
      "resourceName": "${TBSVM_RMQ_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "SQL MI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Storage Space",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A", "type": "math" },
    { "expression": "$E/$D", "type": "math" }
   ]
  },
  {
   "title": "Average CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "avg_cpu_percent",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${TBS_SQLMI_RESOURCE_GROUP}",
      "resourceName": "${TBS_SQLMI_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "avg_cpu_percent",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${NTRC_SQLMI_RESOURCE_GROUP}",
      "resourceName": "${NTRC_SQLMI_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "IO Performance Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }} {{ Metric }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "io_bytes_read",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${TBS_SQLMI_RESOURCE_GROUP}",
      "resourceName": "${TBS_SQLMI_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }} {{ Metric }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "io_bytes_written",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${TBS_SQLMI_RESOURCE_GROUP}",
      "resourceName": "${TBS_SQLMI_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }} {{ Metric }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "io_bytes_read",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${NTRC_SQLMI_RESOURCE_GROUP}",
      "resourceName": "${NTRC_SQLMI_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }} {{ Metric }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "io_bytes_written",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${NTRC_SQLMI_RESOURCE_GROUP}",
      "resourceName": "${NTRC_SQLMI_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "IO Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }} {{ Metric }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "io_requests",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${TBS_SQLMI_RESOURCE_GROUP}",
      "resourceName": "${TBS_SQLMI_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }} {{ Metric }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "io_requests",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${NTRC_SQLMI_RESOURCE_GROUP}",
      "resourceName": "${NTRC_SQLMI_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Service Bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Server Send Latency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerSendLatency",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus Message Count Details",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AbandonMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CompleteMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Size",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Size",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Signal R", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Error Percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SystemErrors",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Connections/Messages Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${INFRA_SHARED_RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${SIGNALR_RESOURCE_NAME}"
     },
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "ConnectionCount",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${INFRA_SHARED_RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${SIGNALR_RESOURCE_NAME}"
     },
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "ConnectionCloseCount",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${INFRA_SHARED_RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${SIGNALR_RESOURCE_NAME}"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "MessageCount",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Traffic Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "InboundTraffic",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "OutboundTraffic",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "APIM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Capacity",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${APIM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Duration of Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 52 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BackendDuration",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${APIM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Duration",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${APIM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 52 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "GatewayResponseCode",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${APIM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  }
 ]
}