{
 "title": "APIM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "sku",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "resources\r\n| where name contains \"apim-ng-infra-shared\"\r\n| project name,sku.name"
     },
     "subscriptions": [ "${SUBSCRIPTION}" ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Capacity",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "GatewayResponseCode",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "resources\r\n| where name contains \"apim-ng-infra-shared\"\r\n| project name,sku.capacity"
     },
     "subscriptions": [ "${SUBSCRIPTION}" ]
    }
   ]
  },
  {
   "title": "subnet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "resources\r\n| where name contains \"apim-ng-infra-shared\"\r\n| project name,subnet_name = split(properties.virtualNetworkConfiguration.subnetResourceId,\"/\")[-1]"
     },
     "subscriptions": [ "${SUBSCRIPTION}" ]
    }
   ]
  },
  {
   "title": "Duration of Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BackendDuration",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Duration",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Error Reason Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.apimanagement/service",
      "dimensionFilters": [
       {
        "dimension": "LastErrorReason",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  }
 ]
}