{
 "title": "SQL MI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "avg_cpu_percent",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "IO Performance",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "io_requests",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "io_bytes_read",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/managedinstances",
      "dimensionFilters": [],
      "metricName": "io_bytes_written",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Storage Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  }
 ]
}