{
 "title": "${DASHBOARD_NAME}",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Bet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bets Poller Event Hub",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet - Last Update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "union isfuzzy=true\r\n    availabilityResults,\r\n    requests,\r\n    exceptions,\r\n    pageViews,\r\n    traces,\r\n    customEvents,\r\n    dependencies\r\n| where message has \"New LastLogPkId\" \r\n| order by timestamp desc\r\n| take 1\r\n| extend \r\n    secondsBefore = datetime_diff('second', now(), timestamp)\r\n| project secondsBefore ",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_RESOURCE_GROUP_DATA}/providers/Microsoft.Insights/components/${BET_RESOURCE_NAME_DATA_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "subscriptions": [ "${SUBSCRIPTION}" ]
    }
   ]
  },
  {
   "title": "Bet - LastPkId",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "union isfuzzy=true\r\n    availabilityResults,\r\n    requests,\r\n    exceptions,\r\n    pageViews,\r\n    traces,\r\n    customEvents,\r\n    dependencies\r\n| where message contains \"New LastLogPkId\"\r\n| order by timestamp desc\r\n| take 1\r\n| extend LastPkId = customDimensions._lastLogPkId\r\n| project LastPkId ",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_RESOURCE_GROUP_DATA}/providers/Microsoft.Insights/components/${BET_RESOURCE_NAME_DATA_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Bet History Service Bus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Scheduled",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "bet-history-fallback" ], "operator": "eq" }
      ],
      "metricName": "ScheduledMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "DLQ",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "bet-history-fallback" ], "operator": "eq" }
      ],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Active Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "bet-history-fallback" ], "operator": "eq" }
      ],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "End to End Bet History Replication Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend Bet_History_Total_Replication_Time_In_MS = todecimal(customDimensions.prop__bet_history_upsert_time)\r\n| where isnotempty(Bet_History_Total_Replication_Time_In_MS)\r\n| project timestamp, Bet_History_Total_Replication_Time_In_MS\r\n| order by timestamp desc",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BETH_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BETH_RESOURCE_NAME_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend Bet_History_Total_Replication_Time_MS = todecimal(customDimensions.prop__bet_history_replication_time)\r\n| where isnotempty(Bet_History_Total_Replication_Time_MS)\r\n| summarize Average_BetReplication_Time_MS = round(avg(Bet_History_Total_Replication_Time_MS), 0) \r\n| project-rename [\"Bet History Total\"] = Average_BetReplication_Time_MS",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BETH_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BETH_RESOURCE_NAME_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend Bet_History_Upsert_Time_MS = todecimal(customDimensions.prop__bet_history_upsert_time)\r\n| where isnotempty(Bet_History_Upsert_Time_MS)\r\n| summarize \r\n    4_Average_Bet_History_Upsert_Time_MS = round(avg(Bet_History_Upsert_Time_MS), 0) \r\n| project-rename [\"BetHistory Upsert\"] = 4_Average_Bet_History_Upsert_Time_MS\r\n\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BETH_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BETH_RESOURCE_NAME_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend Bet_To_LogBet_Replication_Time_In_MS = todecimal(customDimensions.tbs_bet_to_log_bet_time)\r\n| where isnotempty(Bet_To_LogBet_Replication_Time_In_MS)\r\n| summarize 1_Average_Bet_To_LogBet_Replication_Time_MS = round(avg(Bet_To_LogBet_Replication_Time_In_MS), 0)\r\n| project-rename [\"Bet to LogBet\"] = 1_Average_Bet_To_LogBet_Replication_Time_MS",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_RESOURCE_GROUP_DATA}/providers/Microsoft.Insights/components/${BET_RESOURCE_NAME_DATA_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend LogBet_To_TBS_Poller_Time_In_MS = todecimal(customDimensions.tbs_log_bet_poll_time)\r\n| where isnotempty(LogBet_To_TBS_Poller_Time_In_MS)\r\n// | project timestamp, LogBet_To_TBS_Poller_Time_In_MS\r\n| summarize 2_Average_LogBet_To_TBS_Poller_Time_MS = round(avg(LogBet_To_TBS_Poller_Time_In_MS), 0)\r\n| project-rename [\"LogBet to TBS Poller\"] = 2_Average_LogBet_To_TBS_Poller_Time_MS",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_RESOURCE_GROUP_DATA}/providers/Microsoft.Insights/components/${BET_RESOURCE_NAME_DATA_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend EventHub_To_Consumer_Time_MS = todecimal(customDimensions.prop__bet_history_writerreceived_time)\r\n| where isnotempty(EventHub_To_Consumer_Time_MS)\r\n| summarize 3_Average_EventHub_To_Consumer_Time_MS = round(avg(EventHub_To_Consumer_Time_MS), 0)\r\n| project-rename [\"EH to BetHistory\"] = 3_Average_EventHub_To_Consumer_Time_MS\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BETH_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BETH_RESOURCE_NAME_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Bets EventHub Namespace Size",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend Bet_History_Total_Replication_Time_MS = todecimal(customDimensions.prop__bet_domain_replication_time)\r\n| where isnotempty(Bet_History_Total_Replication_Time_MS)\r\n| summarize Average_BetReplication_Time_MS = round(avg(Bet_History_Total_Replication_Time_MS), 0) \r\n| project-rename [\"Bet Domain Total\"] = Average_BetReplication_Time_MS",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_RESOURCE_GROUP_DATA}/providers/Microsoft.Insights/components/${BET_RESOURCE_NAME_DATA_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend Bet_History_Upsert_Time_MS = todecimal(customDimensions.prop__bet_domain_upsert_time)\r\n| where isnotempty(Bet_History_Upsert_Time_MS)\r\n| summarize \r\n    4_Average_Bet_History_Upsert_Time_MS = round(avg(Bet_History_Upsert_Time_MS), 0) \r\n| project-rename [\"BetDomain Upsert\"] = 4_Average_Bet_History_Upsert_Time_MS\r\n\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_RESOURCE_GROUP_DATA}/providers/Microsoft.Insights/components/${BET_RESOURCE_NAME_DATA_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend EventHub_To_Consumer_Time_MS = todecimal(customDimensions.prop__bet_domain_writer_received_time)\r\n| where isnotempty(EventHub_To_Consumer_Time_MS)\r\n| summarize 3_Average_EventHub_To_Consumer_Time_MS = round(avg(EventHub_To_Consumer_Time_MS), 0)\r\n| project-rename [\"EH to BetDomain\"] = 3_Average_EventHub_To_Consumer_Time_MS\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_RESOURCE_GROUP_DATA}/providers/Microsoft.Insights/components/${BET_RESOURCE_NAME_DATA_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Bets Poller Event Hub",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Domain Service Bus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Scheduled",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "bet-domain-fallback" ], "operator": "eq" }
      ],
      "metricName": "ScheduledMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "DLQ",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "bet-domain-fallback" ], "operator": "eq" }
      ],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Active Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "bet-domain-fallback" ], "operator": "eq" }
      ],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "End to End Bet Domain Replication Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend Bet_History_Total_Replication_Time_In_MS = todecimal(customDimensions.prop__bet_domain_upsert_time)\r\n| where isnotempty(Bet_History_Total_Replication_Time_In_MS)\r\n| project timestamp, Bet_History_Total_Replication_Time_In_MS\r\n| order by timestamp desc",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_RESOURCE_GROUP_DATA}/providers/Microsoft.Insights/components/${BET_RESOURCE_NAME_DATA_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Account - v2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Poller Event Hub",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Client - Last Update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| project pollerTimestamp=timestamp, name, type, lastPKId = tostring(customDimensions.LogPKId)\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller Client\"\r\n| order by pollerTimestamp desc\r\n| take 1;\r\nlet writerLog = traces\r\n| project writerTimestamp=timestamp, domain = customDimensions.Domain, lastPKId = tostring(customDimensions.LastPKId)\r\n| where domain == \"User\"\r\n| where lastPKId != \"\"\r\n| order by writerTimestamp desc\r\n| take 1;\r\nprint Poller = toscalar ( pollerLog ), Writer = toscalar (writerLog)\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Client - LastPkId",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller Client\"\r\n| order by timestamp desc\r\n| take 1\r\n| project pollerLastPKId = customDimensions.LogPKId;\r\nlet writerLog = traces\r\n| where customDimensions.Domain == \"User\"\r\n| where customDimensions.LastPKId != \"\"\r\n| order by timestamp desc\r\n| take 1\r\n| project customDimensions.LastPKId;\r\nprint Poller=toscalar(pollerLog), Writer=toscalar(writerLog)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Client Service Bus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Scheduled",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "account-domain-user-fallback" ], "operator": "eq" }
      ],
      "metricName": "ScheduledMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "DLQ",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "account-domain-user-fallback" ], "operator": "eq" }
      ],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Active Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "account-domain-user-fallback" ], "operator": "eq" }
      ],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "E2E Client Replication Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| project pollerTimestamp=timestamp, name, type, lastPKId = tostring(customDimensions.LogPKId)\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller Client\"  // Possible values Poller Client, Poller Account, Poller ClientLimit, Poller AcTransaction, Poller ClientBankDetail, Poller ClientSelfExclusion,\r\n| order by pollerTimestamp desc;\r\nlet writerLog = traces\r\n| project writerTimestamp=timestamp, domain = customDimensions.Domain, lastPKId = tostring(customDimensions.LastPKId), latency = timestamp - customDimensions.LogDateTime\r\n| where domain == \"User\" // Possible Valies User, Wallet, RSG, TransactionHistory, Payment\r\n| where lastPKId != \"\"\r\n| order by writerTimestamp desc;\r\npollerLog\r\n| join kind=inner writerLog on lastPKId\r\n| project\r\n    latencyInMilliseconds = latency / time(1ms),\r\n    writerTimestamp\r\n| order by writerTimestamp",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Account EventHub Namespace Size",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Poller Event Hub",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Account - Last Update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| project pollerTimestamp=timestamp, name, type, lastPKId = tostring(customDimensions.LogPKId)\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller Account\"\r\n| order by pollerTimestamp desc\r\n| take 1;\r\nlet writerLog = traces\r\n| project writerTimestamp=timestamp, domain = customDimensions.Domain, lastPKId = tostring(customDimensions.LastPKId)\r\n| where domain == \"Wallet\"\r\n| where lastPKId != \"\"\r\n| order by writerTimestamp desc\r\n| take 1;\r\nprint Poller = toscalar ( pollerLog ), Writer = toscalar (writerLog)\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Account - LastPkId",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller Account\"\r\n| order by timestamp desc\r\n| take 1\r\n| project pollerLastPKId = customDimensions.LogPKId;\r\nlet writerLog = traces\r\n| where customDimensions.Domain == \"Wallet\"\r\n| where customDimensions.LastPKId != \"\"\r\n| order by timestamp desc\r\n| take 1\r\n| project customDimensions.LastPKId;\r\nprint Poller=toscalar(pollerLog), Writer=toscalar(writerLog)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Account Service Bus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Scheduled",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "account-domain-wallet-fallback" ], "operator": "eq" }
      ],
      "metricName": "ScheduledMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "DLQ",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "account-domain-wallet-fallback" ], "operator": "eq" }
      ],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Active Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "account-domain-wallet-fallback" ], "operator": "eq" }
      ],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "E2E Account Replication Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| project pollerTimestamp=timestamp, name, type, lastPKId = tostring(customDimensions.LogPKId)\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller Account\"  // Possible values Poller Client, Poller Account, Poller ClientLimit, Poller AcTransaction, Poller ClientBankDetail, Poller ClientSelfExclusion,\r\n| order by pollerTimestamp desc;\r\nlet writerLog = traces\r\n| project writerTimestamp=timestamp, domain = customDimensions.Domain, lastPKId = tostring(customDimensions.LastPKId), latency = timestamp - customDimensions.LogDateTime\r\n| where domain == \"Wallet\" // Possible Valies User, Wallet, RSG, TransactionHistory, Payment\r\n| where lastPKId != \"\"\r\n| order by writerTimestamp desc;\r\npollerLog\r\n| join kind=inner writerLog on lastPKId\r\n| project\r\n    latencyInMilliseconds = latency / time(1ms),\r\n    writerTimestamp\r\n| order by writerTimestamp",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "ClientLimit - Last Update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| project pollerTimestamp=timestamp, name, type, lastPKId = tostring(customDimensions.LogPKId)\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller ClientLimit\"\r\n| order by pollerTimestamp desc\r\n| take 1;\r\nlet writerLog = traces\r\n| project writerTimestamp=timestamp, domain = customDimensions.Domain, lastPKId = tostring(customDimensions.LastPKId)\r\n| where domain == \"RSG\"\r\n| where lastPKId != \"\"\r\n| order by writerTimestamp desc\r\n| take 1;\r\nprint Poller = toscalar ( pollerLog ), Writer = toscalar (writerLog)\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "ClientLimit - LastPkId",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller ClientLimit\"\r\n| order by timestamp desc\r\n| take 1\r\n| project pollerLastPKId = customDimensions.LogPKId;\r\nlet writerLog = traces\r\n| where customDimensions.Domain == \"RSG\"\r\n| where customDimensions.LastPKId != \"\"\r\n| order by timestamp desc\r\n| take 1\r\n| project customDimensions.LastPKId;\r\nprint Poller=toscalar(pollerLog), Writer=toscalar(writerLog)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "ClientLimit Service Bus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Scheduled",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "account-domain-rsg-fallback" ], "operator": "eq" }
      ],
      "metricName": "ScheduledMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "DLQ",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "account-domain-rsg-fallback" ], "operator": "eq" }
      ],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Active Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "account-domain-rsg-fallback" ], "operator": "eq" }
      ],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "E2E ClientLimit Replication Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| project pollerTimestamp=timestamp, name, type, lastPKId = tostring(customDimensions.LogPKId)\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller ClientLimit\"  // Possible values Poller Client, Poller Account, Poller ClientLimit, Poller AcTransaction, Poller ClientBankDetail, Poller ClientSelfExclusion,\r\n| order by pollerTimestamp desc;\r\nlet writerLog = traces\r\n| project writerTimestamp=timestamp, domain = customDimensions.Domain, lastPKId = tostring(customDimensions.LastPKId), latency = timestamp - customDimensions.LogDateTime\r\n| where domain == \"RSG\" // Possible Valies User, Wallet, RSG, TransactionHistory, Payment\r\n| where lastPKId != \"\"\r\n| order by writerTimestamp desc;\r\npollerLog\r\n| join kind=inner writerLog on lastPKId\r\n| project\r\n    latencyInMilliseconds = latency / time(1ms),\r\n    writerTimestamp\r\n| order by writerTimestamp",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "AcTransaction - Last Update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| project pollerTimestamp=timestamp, name, type, lastPKId = tostring(customDimensions.LogPKId)\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller AcTransaction\"\r\n| order by pollerTimestamp desc\r\n| take 1;\r\nlet writerLog = traces\r\n| project writerTimestamp=timestamp, domain = customDimensions.Domain, lastPKId = tostring(customDimensions.LastPKId)\r\n| where domain == \"TransactionHistory\"\r\n| where lastPKId != \"\"\r\n| order by writerTimestamp desc\r\n| take 1;\r\nprint Poller = toscalar ( pollerLog ), Writer = toscalar (writerLog)\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "AcTransaction - LastPkId",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller AcTransaction\"\r\n| order by timestamp desc\r\n| take 1\r\n| project pollerLastPKId = customDimensions.LogPKId;\r\nlet writerLog = traces\r\n| where customDimensions.Domain == \"TransactionHistory\"\r\n| where customDimensions.LastPKId != \"\"\r\n| order by timestamp desc\r\n| take 1\r\n| project customDimensions.LastPKId;\r\nprint Poller=toscalar(pollerLog), Writer=toscalar(writerLog)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "AcTransaction Service Bus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Scheduled",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "account-domain-actransaction-fallback"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "ScheduledMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "DLQ",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "account-domain-actransaction-fallback"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Active Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "account-domain-actransaction-fallback"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${RESOURCE_GROUP_INFRA}",
      "resourceName": "${RESOURCE_NAME_INFRA_SB}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "E2E AcTransaction Replication Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| project pollerTimestamp=timestamp, name, type, lastPKId = tostring(customDimensions.LogPKId)\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller AcTransaction\"  // Possible values Poller Client, Poller Account, Poller ClientLimit, Poller AcTransaction, Poller ClientBankDetail, Poller ClientSelfExclusion,\r\n| order by pollerTimestamp desc;\r\nlet writerLog = traces\r\n| project writerTimestamp=timestamp, domain = customDimensions.Domain, lastPKId = tostring(customDimensions.LastPKId), latency = timestamp - customDimensions.LogDateTime\r\n| where domain == \"TransactionHistory\" // Possible Valies User, Wallet, RSG, TransactionHistory, Payment\r\n| where lastPKId != \"\"\r\n| order by writerTimestamp desc;\r\npollerLog\r\n| join kind=inner writerLog on lastPKId\r\n| project\r\n    latencyInMilliseconds = latency / time(1ms),\r\n    writerTimestamp\r\n| order by writerTimestamp",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "ClientSelfExclusion - Last Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| project pollerTimestamp=timestamp, name, type, lastPKId = tostring(customDimensions.LogPKId)\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller ClientSelfExclusion\"\r\n| order by pollerTimestamp desc\r\n| take 1;\r\nprint Poller = toscalar ( pollerLog )\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "ClientSelfExclusion - LastPkId",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let pollerLog = dependencies\r\n| where type == \"Poller_Event\"\r\n| where name == \"Poller ClientSelfExclusion\"\r\n| order by timestamp desc\r\n| take 1\r\n| project pollerLastPKId = customDimensions.LogPKId;\r\nprint Poller=toscalar(pollerLog)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${ACC_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${ACC_RESOURCE_NAME_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Racing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Racing Poller Event Hub",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "App Exception Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 36 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Poller Web App",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [
       {
        "dimension": "cloud/roleName",
        "filters": [
         "${ENVIRONMENT}-webapp-ng-racing-datatools-tbspollerracing-eau"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RACING_RESOURCE_GROUP_DATA}",
      "resourceName": "${RACING_RESOURCE_NAME_DATA_AI}",
      "timeGrain": "PT1H"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Consumer Func App",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [
       {
        "dimension": "cloud/roleName",
        "filters": [
         "${ENVIRONMENT}-fnapp-ng-racing-datatools-eventhubconsumer-eau"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RACING_RESOURCE_GROUP_DATA}",
      "resourceName": "${RACING_RESOURCE_NAME_DATA_AI}",
      "timeGrain": "PT1H"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Racing Event Hub Namespace Size",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Racing Poller Event Hub",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_NAME_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  }
 ]
}