{
 "title": "SRE Summary - ${ENVIRONMENT}",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Failures & Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Signal R Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SystemErrors",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "APIM Errors",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.apimanagement/service",
      "dimensionFilters": [
       {
        "dimension": "LastErrorReason",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${APIM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB 429 Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${DOINGRESS_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_DOINGRESS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${PAYMENT_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_PAYMENT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_RACING_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RSG_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_RSG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${USER_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_USER_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${WALLET_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_WALLET_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub Quotation Exceeded Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${EH_ACCOUNT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${EH_BET_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${PROMOTION_RESOURCE_GROUP}",
      "resourceName": "${EH_PROMOTION_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${EH_RACING_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub - Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${EH_ACCOUNT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${EH_BET_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${PROMOTION_RESOURCE_GROUP}",
      "resourceName": "${EH_PROMOTION_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${EH_RACING_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Postgres Connection Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connections_failed",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${PSQL_ACCOUNT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connections_failed",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${PSQL_BET_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connections_failed",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${PSQL_RACING_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "SignalR Connection Quota Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${INFRA_SHARED_RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${SIGNALR_RESOURCE_NAME}"
     },
     "azureMonitor": {
      "aggregation": "Minimum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "ConnectionQuotaUtilization",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "APIM Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Capacity",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${APIM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus Message Count Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AbandonMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CompleteMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SB_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "EvenHub Namespace Size - Bet",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${EH_BET_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "EvenHub Namespace Size - Racing",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${EH_RACING_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "EvenHub Namespace Size - Promotion",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${PROMOTION_RESOURCE_GROUP}",
      "resourceName": "${EH_PROMOTION_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "EvenHub Namespace Size - Account",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${EH_ACCOUNT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB RU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "customNamespace": "microsoft.documentdb/databaseaccounts",
      "dimensionFilters": [],
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${DOINGRESS_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_DOINGRESS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "customNamespace": "microsoft.documentdb/databaseaccounts",
      "dimensionFilters": [],
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${PAYMENT_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_PAYMENT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "customNamespace": "microsoft.documentdb/databaseaccounts",
      "dimensionFilters": [],
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_RACING_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "customNamespace": "microsoft.documentdb/databaseaccounts",
      "dimensionFilters": [],
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RSG_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_RSG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "customNamespace": "microsoft.documentdb/databaseaccounts",
      "dimensionFilters": [],
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${WALLET_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_WALLET_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "TBS Available Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBS_RESOURCE_GROUP}",
      "resourceName": "${TBS_VM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "SQL MI Storage Space",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Cosmos DB Data Usage - doingress",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DataUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${DOINGRESS_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_DOINGRESS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB Data Usage - User",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DataUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${USER_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_USER_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB Data Usage -payment",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DataUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${PAYMENT_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_PAYMENT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB Data Usage - Rsg",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DataUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RSG_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_RSG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Postgres Storage Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${PSQL_ACCOUNT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${PSQL_BET_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${PSQL_RACING_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB Data Usage - Racing",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DataUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_RACING_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB Data Usage - Wallet",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DataUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${WALLET_RESOURCE_GROUP}",
      "resourceName": "${DOCDB_WALLET_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Signal R Performance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerLoad",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${SIGNALR_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "APIM Duration of Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BackendDuration",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${APIM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Duration",
      "metricNamespace": "microsoft.apimanagement/service",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${APIM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "App Service Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_XL_RESOURCE_GROUP}",
      "resourceName": "${WEBAPP_BET_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${WEBAPP_ACCOUNT_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${WEBAPP_PROMO_XL_RESOURCE_GROUP}",
      "resourceName": "${WEBAPP_PROMO_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_XL_RESOURCE_GROUP}",
      "resourceName": "${WEBAPP_BET_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "TBS VM CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBS_RESOURCE_GROUP}",
      "resourceName": "${TBS_VM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "SQL MI Average CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 4, "y": 48 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "avg_cpu_percent",
      "metricNamespace": "microsoft.sql/managedinstances",
      "resourceGroup": "${SQLMI_RESOURCE_GROUP}",
      "resourceName": "${SQLMI_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "TBS VM Disk Performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 48 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Read Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBS_RESOURCE_GROUP}",
      "resourceName": "${TBS_VM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Write Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBS_RESOURCE_GROUP}",
      "resourceName": "${TBS_VM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Read Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBS_RESOURCE_GROUP}",
      "resourceName": "${TBS_VM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Write Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "${TBS_RESOURCE_GROUP}",
      "resourceName": "${TBS_VM_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "App Service Plan CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ASP_ACCOUNT_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ASP_ACCOUNT_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ASP_ACCOUNT_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${ASP_BET_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${ASP_BET_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${ASP_BET_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${CONSOLE_ENGINE_RESOURCE_GROUP}",
      "resourceName": "${ASP_CONSOLE_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${PROMOTION_RESOURCE_GROUP}",
      "resourceName": "${ASP_PROMO_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${PROMOTION_RESOURCE_GROUP}",
      "resourceName": "${ASP_PROMO_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${PROMOTION_RESOURCE_GROUP}",
      "resourceName": "${ASP_PROMO_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${ASP_RACING_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${ASP_RACING_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${ASP_RACING_FEED_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${ASP_RACING_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "App Service Plan Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ASP_ACCOUNT_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ASP_ACCOUNT_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ASP_ACCOUNT_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${ASP_BET_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${ASP_BET_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${ASP_BET_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${CONSOLE_ENGINE_RESOURCE_GROUP}",
      "resourceName": "${ASP_CONSOLE_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${PROMOTION_RESOURCE_GROUP}",
      "resourceName": "${ASP_PROMO_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${PROMOTION_RESOURCE_GROUP}",
      "resourceName": "${ASP_PROMO_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${PROMOTION_RESOURCE_GROUP}",
      "resourceName": "${ASP_PROMO_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${ASP_RACING_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${ASP_RACING_ENGINE_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${ASP_RACING_FEED_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_RESOURCE_GROUP}",
      "resourceName": "${ASP_RACING_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "App Insight Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Account AI Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 63 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "XL ",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${AI_ACCOUNT_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Payment",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${PAYMENT_RESOURCE_GROUP}",
      "resourceName": "${AI_PAYMENT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Datatools",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_AC_DT_RESOURCE_GROUP}",
      "resourceName": "${AI_AC_DT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Salesforce",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_AC_SF_RESOURCE_GROUP}",
      "resourceName": "${AI_AC_SF_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Wallet",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${WALLET_RESOURCE_GROUP}",
      "resourceName": "${AI_WALLET_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Account AI Dependencies Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 63 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "XL ",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${AI_ACCOUNT_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Payment",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${PAYMENT_RESOURCE_GROUP}",
      "resourceName": "${AI_PAYMENT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Datatools",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_AC_DT_RESOURCE_GROUP}",
      "resourceName": "${AI_AC_DT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Salesforce",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_AC_SF_RESOURCE_GROUP}",
      "resourceName": "${AI_AC_SF_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Wallet",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${WALLET_RESOURCE_GROUP}",
      "resourceName": "${AI_WALLET_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Account AI Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 63 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "RSG",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RSG_RESOURCE_GROUP}",
      "resourceName": "${AI_RSG_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "TransHistory",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_TRANSHISTORY_ENG_RESOURCE_GROUP}",
      "resourceName": "${AI_TRANSHISTORY_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "KYC",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_KYC_ENG_RESOURCE_GROUP}",
      "resourceName": "${AI_KYC_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "User",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${USER_RESOURCE_GROUP}",
      "resourceName": "${AI_USER_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Account AI Dependencies Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 63 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "RSG",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RSG_RESOURCE_GROUP}",
      "resourceName": "${AI_RSG_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "TransHistory",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_TRANSHISTORY_ENG_RESOURCE_GROUP}",
      "resourceName": "${AI_TRANSHISTORY_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "KYC",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_KYC_ENG_RESOURCE_GROUP}",
      "resourceName": "${AI_KYC_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "User",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${USER_RESOURCE_GROUP}",
      "resourceName": "${AI_USER_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet AI Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 69 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "XL",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_XL_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "BetPlacement",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_BET_PLACEMENT_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_PLACEMENT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "DataTools",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_BET_DATA_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "BetHistory",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_BET_HISTORY_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_HISTORY_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "BetIntercept",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_INTERCEPT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet AI Dependencies Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 69 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "XL",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_XL_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "BetPlacement",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_BET_PLACEMENT_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_PLACEMENT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "DataTools",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_BET_DATA_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "BetHistory",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_BET_HISTORY_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_HISTORY_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "BetIntercept",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${AI_BET_INTERCEPT_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Feeds AI Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 69 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "DOIngress",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${DOINGRESS_RESOURCE_GROUP}",
      "resourceName": "${AI_DOINGRESS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "DOHandler",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_DOHANDLER_RESOURCE_GROUP}",
      "resourceName": "${AI_DOHANDLER_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "TabIngress",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_TABINGRES_RESOURCE_GROUP}",
      "resourceName": "${AI_TABINGRES_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "TabHandler",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_TABHANDLER_RESOURCE_GROUP}",
      "resourceName": "${AI_TABHANDLER_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Feeds AI Dependencies Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 69 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "DOIngress",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${DOINGRESS_RESOURCE_GROUP}",
      "resourceName": "${AI_DOINGRESS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "DOHandler",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_DOHANDLER_RESOURCE_GROUP}",
      "resourceName": "${AI_DOHANDLER_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "TabIngress",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_TABINGRES_RESOURCE_GROUP}",
      "resourceName": "${AI_TABINGRES_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "TabHandler",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_TABHANDLER_RESOURCE_GROUP}",
      "resourceName": "${AI_TABHANDLER_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Racing AI Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "XL",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_RACING_XL_RESOURCE_GROUP}",
      "resourceName": "${AI_RACING_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Engine",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_RACING_ENG_RESOURCE_GROUP}",
      "resourceName": "${AI_RACING_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "DataTools",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_RACING_DATA_RESOURCE_GROUP}",
      "resourceName": "${AI_RACING_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Racing AI Dependencies Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "XL",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_RACING_XL_RESOURCE_GROUP}",
      "resourceName": "${AI_RACING_XL_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Engine",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_RACING_ENG_RESOURCE_GROUP}",
      "resourceName": "${AI_RACING_ENG_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "DataTools",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_RACING_DATA_RESOURCE_GROUP}",
      "resourceName": "${AI_RACING_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "AI Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "TBSCrud",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_TBSCRUD_RESOURCE_GROUP}",
      "resourceName": "${AI_TBSCRUD_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Console",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_CONSOLE_CMS_RESOURCE_GROUP}",
      "resourceName": "${AI_CONSOLE_CMS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Promo Datatools",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_PROMO_DATA_RESOURCE_GROUP}",
      "resourceName": "${AI_PROMO_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Promo Salesforce",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_AC_SF_RESOURCE_GROUP}",
      "resourceName": "${AI_AC_SF_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "AI Dependencies Failures",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "TBSCrud",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_TBSCRUD_RESOURCE_GROUP}",
      "resourceName": "${AI_TBSCRUD_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Console",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_CONSOLE_CMS_RESOURCE_GROUP}",
      "resourceName": "${AI_CONSOLE_CMS_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Promo Datatools",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_PROMO_DATA_RESOURCE_GROUP}",
      "resourceName": "${AI_PROMO_DATA_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Promo Salesforce",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${AI_AC_SF_RESOURCE_GROUP}",
      "resourceName": "${AI_AC_SF_RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  }
 ]
}