{
 "title": "SignalR Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "System Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${RESOURCE_NAME}"
     },
     "azureMonitor": {
      "aggregation": "Minimum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "ConnectionQuotaUtilization",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerLoad",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Traffic Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "InboundTraffic",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "OutboundTraffic",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SystemErrors",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Connections/Messages Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${RESOURCE_NAME}"
     },
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "ConnectionCount",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${RESOURCE_NAME}"
     },
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "ConnectionCloseCount",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${RESOURCE_NAME}"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.signalrservice/signalr",
      "dimensionFilters": [],
      "metricName": "MessageCount",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${RESOURCE_GROUP}",
      "resourceName": "${RESOURCE_NAME}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  }
 ]
}