{
 "title": "Racing Summary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Markets Update EH Trigger Failures",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingMarketsUpdateEventHubTrigger Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RACING_DATATOOL_RESOURCE_GROUP}",
      "resourceName": "${RACING_DATATOOL_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Tab Ingress - Outbound",
   "type": "piechart",
   "description": "% Meetings Publish EventHub",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "// Tab Ingress - Outbound\r\ndependencies\r\n| where type == \"Azure Event Hubs\" and name == \"EventHubProducerClient.Send\" and $__timeFilter(timestamp)\r\n| extend sentOk = success == true\r\n| summarize MsgSent=countif(sentOk), MsgTotal=count(), LatestTimestamp = max(timestamp)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${TABINGRESS_ENG_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${TABINGRESS_ENG_RESOURCE_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Markets Update EH Trigger Max Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 8, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingMarketsUpdateEventHubTrigger MaxDurationMs",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RACING_DATATOOL_RESOURCE_GROUP}",
      "resourceName": "${RACING_DATATOOL_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingMarketsUpdateEventHubTrigger Count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RACING_DATATOOL_RESOURCE_GROUP}",
      "resourceName": "${RACING_DATATOOL_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "DO Ingress - Fail-Safe",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "// DO Ingress Fail-Safe (Inbound/Outbound)\r\ntraces\r\n| where cloud_RoleName has \"doingress-eng-engine\" and $__timeFilter(timestamp)\r\n| where  message startswith \"[Fail-Safe] Process delayed message\"\r\n        or message has \"Update race.\"\r\n| extend IsRaceCheckOps = message startswith \"[Fail-Safe] Process delayed message\"\r\n| extend IsRaceUpdateOps = message has \"Update race.\"\r\n| extend Ops=iff(IsRaceCheckOps, \"Check\", \"Update\")\r\n| extend MessageBody = parse_json(tostring(customDimensions.prop__body))\r\n| extend MeetingId = iff(isempty(MessageBody), tostring(customDimensions.prop__meetingId), MessageBody.meetingId)\r\n| extend RaceNumber = iff(isempty(MessageBody), tostring(customDimensions.prop__raceNumber), MessageBody.raceNumber)\r\n| extend RaceIdentity = strcat(MeetingId, \"-\", RaceNumber)\r\n| project timestamp, RaceIdentity, Ops\r\n| summarize Count=dcount(RaceIdentity), LatestTimestamp = max(timestamp) by Ops\r\n| order by Ops",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${DOINGRESS_ENG_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${DOINGRESS_ENG_RESOURCE_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "SignalR Publisher - Outbound",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "// SignalR Publisher - Outbound\r\ntraces\r\n| where message startswith \"Processing\" and $__timeFilter(timestamp)\r\n| extend InboundType = replace_string(tostring(customDimensions.prop__inboundMessageType), \"Racing.TbsCrud.Models.\", \"\")\r\n| extend OutboundType = replace_string(tostring(customDimensions.prop__outboundMessageType), \"Racing.SignalR.Publisher.Model.\", \"\")\r\n| extend TbsRaceId = replace_string(tostring(customDimensions.prop__signalRMessageTarget), \"RaceSubscription_\", \"\")\r\n| project timestamp, InboundType, OutboundType, TbsRaceId\r\n| summarize Count = dcount(TbsRaceId), LatestTimestamp = max(timestamp) by InboundType\r\n| order by LatestTimestamp desc",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${SIGR_ENG_RESORUCE_GROUP}/providers/Microsoft.Insights/components/${SIGR_ENG_RESOURCE_AI}"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Event Hub Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "DO Handler - Outbound",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 15 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| where message startswith \"Called TbsCrudEngineApi\" and $__timeFilter(timestamp)\r\n| extend prop__url_ = tostring(customDimensions.prop__url)\r\n| extend prop__apiResponse_ = tostring(customDimensions.prop__apiResponse)\r\n| extend OperationAndResult = strcat(prop__url_, \" - \", tostring(customDimensions.prop__apiResponse))\r\n| summarize Count = count(), LatestTimestamp = max(timestamp) by OperationAndResult\r\n| order by LatestTimestamp desc",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${DOHANDLER_ENG_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${DOHANDLER_ENG_RESOURCE_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "DO Handler - Inbound",
   "type": "barchart",
   "description": "Traffic including live feed subscriptions and manual fetching from DO Ingress",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "// Handler - Inbound Subscription\r\ntraces\r\n| where message startswith \"Handling\" and $__timeFilter(timestamp)\r\n| extend ContractType = replace_string(tostring(customDimensions.prop__contractType), \"Racing.DynamicOdds.Models.\", \"\")\r\n| extend RaceIdentity = strcat(tostring(customDimensions.prop__meetingId), \"-\", tostring(customDimensions.prop__raceNumber))\r\n| project timestamp, ContractType, RaceIdentity\r\n| summarize Count = dcount(RaceIdentity), LatestTimestamp = max(timestamp) by ContractType\r\n| order by LatestTimestamp desc\r\n\r\n\r\n\r\n// traces\r\n// | where message startswith \"Handling\" and $__timeFilter(timestamp)\r\n// | extend ContractType = replace_string(tostring(customDimensions.prop__contractType), \"Feeds.Racing.DynamicOdds.Models.\", \"\")\r\n// | project timestamp, ContractType\r\n// | summarize Count = count(), LatestTimestamp = max(timestamp) by ContractType\r\n// | order by LatestTimestamp desc",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${DOHANDLER_ENG_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${DOHANDLER_ENG_RESOURCE_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "TbsCrud - Inbound",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| where message startswith \"Processing\" and $__timeFilter(timestamp)\r\n| extend OperationAndResult = strcat(operation_Name, \" - \", tostring(customDimensions.prop__result))\r\n| summarize Count = count(), LatestTimestamp = max(timestamp) by OperationAndResult\r\n| order by LatestTimestamp desc\r\n\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${TBSCRUD_ENG_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${TBSCRUD_ENG_RESOURCE_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "DO Ingress - Exceptions",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp)\r\n| extend errorType = replace_string(type, \"Racing.DynamicOdds.Ingress.Core.Exceptions.\", \"\")\r\n| project timestamp, Message = errorType\r\n| summarize Count = count(), LatestTimestamp = max(timestamp) by Message\r\n| order by LatestTimestamp desc",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${DOINGRESS_ENG_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${DOINGRESS_ENG_RESOURCE_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "DO Handler - Model Validation Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| where message startswith \"Model Validation\" and $__timeFilter(timestamp)\r\n| extend prop__type_ = tostring(customDimensions.prop__type)\r\n| extend ErrorMessage_ = tostring(parse_json(tostring(customDimensions.prop__validationResults))[0].ErrorMessage)\r\n| extend OperationAndResult = strcat(prop__type_, \" - \", ErrorMessage_)\r\n| summarize Count = count(), LatestTimestamp = max(timestamp) by OperationAndResult\r\n| order by LatestTimestamp desc",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${DOHANDLER_ENG_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${DOHANDLER_ENG_RESOURCE_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Postgres Connection Failure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connections_failed",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub Namespace Errors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB 429 Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_DOCDB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RACING_DATATOOL_RESOURCE_GROUP}",
      "resourceName": "${RACING_DATATOOL_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RACING_ENG_RESOURCE_GROUP}",
      "resourceName": "${RACING_ENG_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${RACING_XL_RESOURCE_GROUP}",
      "resourceName": "${RACING_XL_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Resource Perfomance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "App Service Plan CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_DATATOOL_RESOURCE_ASP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_ENGINE_RESOURCE_ASP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_FEED_RESOURCE_ASP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_XL_RESOURCE_ASP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "App Service Plan Memory Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_DATATOOL_RESOURCE_ASP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_ENGINE_RESOURCE_ASP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_FEED_RESOURCE_ASP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_XL_RESOURCE_ASP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Postgres Server Performance",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "memory_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Storage Account Used Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ ResourceName }}",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilters": [],
      "metricName": "UsedCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "${RACING_DATATOOL_RESOURCE_GROUP}",
      "resourceName": "${RACING_DOMAIN_RESOURCE_STORAGE}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB Performance ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_DOCDB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [],
      "metricName": "DataUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_DOCDB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [],
      "metricName": "IndexUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_DOCDB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CapturedMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${RACING_SHARED_RESOURCE_GROUP}",
      "resourceName": "${RACING_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  }
 ]
}