{
 "title": "Bet Summary",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bet Placements Average Duration in Ms - Racing Single",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingSingleBetPlacement AvgDurationMs",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Placements Average Duration in Ms - Racing Exotic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingExoticBetPlacement AvgDurationMs",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Placements Average Duration in Ms - Racing Multiple",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingMultiplesBetPlacement AvgDurationMs",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "End to End Bet Replication Time (Avg every 30sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend Bet_Replication_Time = todecimal(customDimensions.prop__bet_replication_time)\r\n| extend Bet_Count = toint(customDimensions.prop__bets)\r\n| where isnotempty(Bet_Replication_Time)\r\n| project Bet_Replication_Time, Bet_Count, timestamp, customDimensions\r\n| order by Bet_Count, Bet_Replication_Time, timestamp desc\r\n| summarize Average_BetReplication_Time = avg(Bet_Replication_Time), Average_Bet_Count = avg(Bet_Count) by bin(timestamp, 30s)\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${AI_BET_DATA_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BET_DATA_RESOURCE_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Bet to LogBet Replication Time (Spanshot from Each Batch)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend Bet_To_LogBet_Replication_Time_In_MS = todecimal(customDimensions.tbs_bet_to_log_bet_time)\r\n| where isnotempty(Bet_To_LogBet_Replication_Time_In_MS)\r\n| project timestamp, Bet_To_LogBet_Replication_Time_In_MS\r\n| order by timestamp desc ",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${AI_BET_DATA_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BET_DATA_RESOURCE_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Bet Batch Poll and Map Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend LogBet_To_TBS_Poller_Time_In_MS = todecimal(customDimensions.tbs_log_bet_poll_time)\r\n| where isnotempty(LogBet_To_TBS_Poller_Time_In_MS)\r\n| project timestamp, LogBet_To_TBS_Poller_Time_In_MS\r\n| order by timestamp desc \r\n\r\n",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${AI_BET_DATA_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BET_DATA_RESOURCE_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "TBS Bet Placement Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend RacingSingleBetPlacement = todecimal(customDimensions.prop__tbs_processing_time)\r\n| where isnotempty(RacingSingleBetPlacement) and operation_Name == \"RacingSingleBetPlacement\"\r\n| project timestamp, RacingSingleBetPlacement\r\n| order by timestamp desc \r\n  ",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_PLACE_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BET_PLACE_RESOURCE_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend RacingExoticBetPlacement = todecimal(customDimensions.prop__tbs_processing_time)\r\n| where isnotempty(RacingExoticBetPlacement) and operation_Name == \"RacingExoticBetPlacement\"\r\n| project timestamp, RacingExoticBetPlacement\r\n| order by timestamp desc \r\n  ",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_PLACE_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BET_PLACE_RESOURCE_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend RacingMultiplesBetPlacement = todecimal(customDimensions.prop__tbs_processing_time)\r\n| where isnotempty(RacingMultiplesBetPlacement) and operation_Name == \"RacingMultiplesBetPlacement\"\r\n| project timestamp, RacingMultiplesBetPlacement\r\n| order by timestamp desc \r\n  ",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_PLACE_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BET_PLACE_RESOURCE_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| extend RacingMultiFixedBetPlacement = todecimal(customDimensions.prop__tbs_processing_time)\r\n| where isnotempty(RacingMultiFixedBetPlacement) and operation_Name == \"RacingMultiFixedBetPlacement\"\r\n| project timestamp, RacingMultiFixedBetPlacement\r\n| order by timestamp desc \r\n  ",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_PLACE_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BET_PLACE_RESOURCE_AI}",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Bet Domain Writer Fallback Message Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| where message has \"Sending bet ids to fallback queue\" \r\n| order by timestamp desc\r\n| project operation_Name,timestamp,operation_Id \r\n| summarize Count = dcount(operation_Id) by bin(timestamp, 5s)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${AI_BET_DATA_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BET_DATA_RESOURCE_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "subscriptions": [ "${SUBSCRIPTION}" ]
    }
   ]
  },
  {
   "title": "Bet History Writer Fallback Message Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| where message has \"Sending event to fallback\" \r\n| order by timestamp desc\r\n| project operation_Name,timestamp,operation_Id \r\n| summarize Count = dcount(operation_Id) by bin(timestamp, 5s)",
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${BET_HISTORY_RESOURCE_GROUP}/providers/Microsoft.Insights/components/${BET_HISTORY_RESOURCE_AI}",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "subscriptions": [ "${SUBSCRIPTION}" ]
    }
   ]
  },
  {
   "title": "Bet Intercept App Service",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AverageMemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet XL App Service",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AverageMemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Placement App Service",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AverageMemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "PSQL Performance",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "memory_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB Performance",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000
      ],
      "dimensionFilters": [],
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${PAYMENT_RESOURCE_GROUP}",
      "resourceName": "${PAYMENT_RESOURCE_DOCDB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [],
      "metricName": "DataUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${PAYMENT_RESOURCE_GROUP}",
      "resourceName": "${PAYMENT_RESOURCE_DOCDB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub Performance",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.servicebus/namespaces",
      "dimensionFilters": [],
      "metricName": "Size",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.servicebus/namespaces",
      "dimensionFilters": [],
      "metricName": "IncomingRequests",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.servicebus/namespaces",
      "dimensionFilters": [],
      "metricName": "SuccessfulRequests",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.servicebus/namespaces",
      "dimensionFilters": [],
      "metricName": "CompleteMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.servicebus/namespaces",
      "dimensionFilters": [],
      "metricName": "AbandonMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Placements Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingSingleBetPlacement Count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingSingleBetPlacement Successes",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingMultiplesBetPlacement Count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingMultiplesBetPlacement Successes",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingExoticBetPlacement Count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.eventhub/namespaces",
      "dimensionFilters": [],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.eventhub/namespaces",
      "dimensionFilters": [],
      "metricName": "IncomingRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.eventhub/namespaces",
      "dimensionFilters": [],
      "metricName": "SuccessfulRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.eventhub/namespaces",
      "dimensionFilters": [],
      "metricName": "ConnectionsOpened",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Bet Failures - Settled Bets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "GetSettledBets Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Failures - Bet Intercept",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "GetBetIntercept Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Failures - Bet Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "GetBetCount Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Failures - Racing Bet Multi",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingBetMulti Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Failures - Racing Exotic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingExotic Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Failures - Render Swagger UI",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RenderSwaggerUI Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Failures - Racing Bet Single",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingBetSingle Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Failures - Racing Multiples",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingMultiples Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Failures - Pending Bets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "GetPendingBets Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Failures - Render Swagger Document",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RenderSwaggerDocument Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Intercept HTTP Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B+$C+$D+$E+$F+$G+$H+$I", "type": "math" }
   ]
  },
  {
   "title": "Bet XL HTTP Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B+$C+$D+$E+$F+$G+$H+$I", "type": "math" }
   ]
  },
  {
   "title": "Bet Placement HTTP Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B+$C+$D+$E+$F+$G+$H+$I", "type": "math" }
   ]
  },
  {
   "title": "Bet Placement Failures",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingSingleBetPlacement Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RacingMultiplesBetPlacement Failures",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet XL Failures",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_AI_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub Failures",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub Failures",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.eventhub/namespaces",
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connections_failed",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.eventhub/namespaces",
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.eventhub/namespaces",
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Resource Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Bet Intercept App Service Requests",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FunctionExecutionCount",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RequestsInApplicationQueue",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet XL App Service Requests",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 4, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FunctionExecutionCount",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RequestsInApplicationQueue",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Placement App Service Requests",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 8, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FunctionExecutionCount",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RequestsInApplicationQueue",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveConnections",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ConnectionsOpened",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ConnectionsClosed",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveConnections",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ConnectionsOpened",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ConnectionsClosed",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Business Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Bet Intercept",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Threads",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AppConnections",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_INTERCEPT_RESOURCE_GROUP}",
      "resourceName": "${BET_INTERCEPT_RESOURCE_fnapp}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet XL",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Threads",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AppConnections",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Bet Placement",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Threads",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AppConnections",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_PLACE_RESOURCE_GROUP}",
      "resourceName": "${BET_PLACE_RESOURCE_FNAPP_API}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "PSQL Performance",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "network_bytes_ingress",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "network_bytes_egress",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "active_connections",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "maximum_used_transactionIDs",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "backup_storage_used",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_credits_consumed",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_credits_remaining",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 97 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${BET_SHARED_RESOURCE_GROUP}",
      "resourceName": "${BET_SHARED_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 97 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingRequests",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulRequests",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_SHARED_RESOURCE_GROUP}",
      "resourceName": "${INFRA_SHARED_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  }
 ]
}