{
 "title": "Account Summary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Failures & Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PSQL Failed Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connections_failed",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub Error",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "XL Service Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_AI}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "XL Service Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http5xx",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http401",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http403",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http404",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${BET_RESOURCE_GROUP}",
      "resourceName": "${BET_RESOURCE_FNAPP_XL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Postgres Storage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${INFRA_RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${INFRA_RESOURCE_SIGR}"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Postgres Storage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${INFRA_RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${INFRA_RESOURCE_SIGR}"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "storage_used",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureLogAnalytics": {
      "resource": "/subscriptions/${SUBSCRIPTION}/resourceGroups/${INFRA_RESOURCE_GROUP}/providers/Microsoft.SignalRService/SignalR/${INFRA_RESOURCE_SIGR}"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "storage_free",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus Message Count Details",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AbandonMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CompleteMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Postgres Connection Quota Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Connection Quota Utilization",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ConnectionQuotaUtilization",
      "metricNamespace": "microsoft.signalrservice/signalr",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SIGR}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB RU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "customNamespace": "microsoft.documentdb/databaseaccounts",
      "dimensionFilters": [],
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${DOINGRESS_RESOURCE_GROUP}",
      "resourceName": "${DOINGRESS_RESOURCE_COSMOSDB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Cosmos DB Data Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilters": [
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DataUsage",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "${DOINGRESS_RESOURCE_GROUP}",
      "resourceName": "${DOINGRESS_RESOURCE_COSMOSDB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Event Hub",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Size",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveConnections",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CapturedBytes",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_EHN}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  { "title": "Business/Resources Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "PSQL CPU/Memory Percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "memory_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "PSQL Disk Performance",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "iops",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "disk_queue_depth",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "read_iops",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "write_iops",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "read_throughput",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "write_throughput",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "PSQL Network Performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "active_connections",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "network_bytes_egress",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "network_bytes_ingress",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_PSQL}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 30 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerSendLatency",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus Queue/Topic",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Messages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ScheduledMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Service Bus Incoming/Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 30 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingRequests",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resourceGroup": "${INFRA_RESOURCE_GROUP}",
      "resourceName": "${INFRA_RESOURCE_SB}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Function App - XL",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_XL_RESOURCE_FNAPP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_XL_RESOURCE_FNAPP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_XL_RESOURCE_FNAPP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AverageMemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_XL_RESOURCE_FNAPP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_XL_RESOURCE_FNAPP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AppConnections",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_XL_RESOURCE_FNAPP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_XL_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_XL_RESOURCE_FNAPP}",
      "timeGrain": "auto"
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "Function App - Sales Force",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_SF_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_SF_RESOURCE_FNAPP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_SF_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_SF_RESOURCE_FNAPP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_SF_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_SF_RESOURCE_FNAPP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AverageMemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_SF_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_SF_RESOURCE_FNAPP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_SF_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_SF_RESOURCE_FNAPP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AppConnections",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_SF_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_SF_RESOURCE_FNAPP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "${ACCOUNT_SF_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_SF_RESOURCE_FNAPP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "App Service Plan - XL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP_XL}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP_XL}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP_XL}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP_XL}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "App Service Plan - Data Tools",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  },
  {
   "title": "App Service Plan - Engine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP_ENG}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP_ENG}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP_ENG}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "${ACCOUNT_RESOURCE_GROUP}",
      "resourceName": "${ACCOUNT_RESOURCE_ASP_ENG}",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "${SUBSCRIPTION}"
    }
   ]
  }
 ]
}